### ISSUE TITLE
Obtaining original BCCWJ corpus

### ISSUE THREAD

**Issue by SpongebobSquamirez** [UniversalDependencies/UD_Japanese-BCCWJ#2]
I tried running the merge command, but nothing seemed to happen. I used a conllu file as the core file, but actually, when I look at what's inside that file, it's only annotations. What is core_SUW.txt? Do I have to purchase that or something?

**Comment by masayu-a** [comment]
You need to purchase the original BCCWJ DVD Edition: https://pj.ninjal.ac.jp/corpus_center/bccwj/en/subscription.html
